import { jest } from '@jest/globals';
import { IndexManager } from '../lib/indexer.js';
import { SkillMetadata, SkillsIndex, Category } from '../lib/types.js';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

describe('IndexManager', () => {
  let indexManager: IndexManager;
  let tempDir: string;
  let indexPath: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'index-test-'));
    indexPath = path.join(tempDir, 'index.json');
    indexManager = new IndexManager(indexPath);
  });

  afterEach(() => {
    if (fs.existsSync(indexPath)) {
      fs.unlinkSync(indexPath);
    }
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  describe('loadIndex', () => {
    it('should create empty index when file does not exist', () => {
      const index = indexManager.loadIndex();

      expect(index.version).toBe('1.0.0');
      expect(index.lastUpdated).toBeDefined();
      expect(Object.keys(index.categories)).toEqual(
        expect.arrayContaining(['方法论', '内容创作', '开发工具', '数据处理', '自动化', '多媒体', '其他'])
      );
      expect(index.skills).toEqual({});
      expect(index.stats.totalSkills).toBe(0);
      expect(index.stats.enabledSkills).toBe(0);
      expect(index.stats.disabledSkills).toBe(0);
    });

    it('should load existing index from file', () => {
      const existingIndex: SkillsIndex = {
        version: '1.0.0',
        lastUpdated: new Date().toISOString(),
        categories: {
          '方法论': ['test-skill'],
          '内容创作': [],
          '开发工具': [],
          '数据处理': [],
          '自动化': [],
          '多媒体': [],
          '其他': []
        },
        skills: {
          'test-skill': {
            name: 'test-skill',
            description: 'Test skill',
            category: '方法论',
            tags: ['test'],
            path: '/path',
            metadataPath: '/path/metadata.json',
            autoGenerated: true,
            customized: false,
            disabled: false
          }
        },
        stats: {
          totalSkills: 1,
          enabledSkills: 1,
          disabledSkills: 0,
          categoryCounts: {
            '方法论': 1,
            '内容创作': 0,
            '开发工具': 0,
            '数据处理': 0,
            '自动化': 0,
            '多媒体': 0,
            '其他': 0
          },
          tagCounts: {
            'test': 1
          }
        }
      };

      fs.writeFileSync(indexPath, JSON.stringify(existingIndex, null, 2));

      const loadedIndex = indexManager.loadIndex();

      expect(loadedIndex.version).toBe('1.0.0');
      expect(loadedIndex.skills['test-skill']).toBeDefined();
      expect(loadedIndex.skills['test-skill'].category).toBe('方法论');
    });

    it('should handle corrupted index file gracefully', () => {
      fs.writeFileSync(indexPath, 'invalid json content');

      const index = indexManager.loadIndex();

      expect(index.version).toBe('1.0.0');
      expect(index.skills).toEqual({});
    });
  });

  describe('saveIndex', () => {
    it('should save index to file with calculated stats', () => {
      const index: SkillsIndex = {
        version: '1.0.0',
        lastUpdated: new Date().toISOString(),
        categories: {
          '方法论': ['skill1', 'skill2'],
          '内容创作': ['skill3'],
          '开发工具': [],
          '数据处理': [],
          '自动化': [],
          '多媒体': [],
          '其他': []
        },
        skills: {
          'skill1': {
            name: 'skill1',
            description: 'Skill 1',
            category: '方法论',
            tags: ['tag1', 'common'],
            path: '/path1',
            metadataPath: '/path1/metadata.json',
            autoGenerated: true,
            customized: false,
            disabled: false
          },
          'skill2': {
            name: 'skill2',
            description: 'Skill 2',
            category: '方法论',
            tags: ['tag2', 'common'],
            path: '/path2',
            metadataPath: '/path2/metadata.json',
            autoGenerated: true,
            customized: false,
            disabled: true
          },
          'skill3': {
            name: 'skill3',
            description: 'Skill 3',
            category: '内容创作',
            tags: ['tag3'],
            path: '/path3',
            metadataPath: '/path3/metadata.json',
            autoGenerated: true,
            customized: false,
            disabled: false
          }
        },
        stats: {
          totalSkills: 0,
          enabledSkills: 0,
          disabledSkills: 0,
          categoryCounts: {} as Record<Category, number>,
          tagCounts: {}
        }
      };

      indexManager.saveIndex(index);

      expect(fs.existsSync(indexPath)).toBe(true);

      const savedContent = fs.readFileSync(indexPath, 'utf-8');
      const savedIndex = JSON.parse(savedContent) as SkillsIndex;

      expect(savedIndex.stats.totalSkills).toBe(3);
      expect(savedIndex.stats.enabledSkills).toBe(2);
      expect(savedIndex.stats.disabledSkills).toBe(1);
      expect(savedIndex.stats.categoryCounts['方法论']).toBe(2);
      expect(savedIndex.stats.categoryCounts['内容创作']).toBe(1);
      expect(savedIndex.stats.tagCounts['common']).toBe(2);
      expect(savedIndex.stats.tagCounts['tag1']).toBe(1);
      expect(savedIndex.lastUpdated).toBeDefined();
    });
  });

  describe('updateSkill', () => {
    it('should add new skill to index', () => {
      const index = indexManager.loadIndex();
      const skillMetadata: SkillMetadata = {
        name: 'new-skill',
        description: 'New skill description',
        category: '开发工具',
        tags: ['tools', 'dev'],
        path: '/new-skill',
        metadataPath: '/new-skill/metadata.json',
        autoGenerated: true,
        customized: false,
        disabled: false
      };

      indexManager.updateSkill(index, skillMetadata);

      expect(index.skills['new-skill']).toBeDefined();
      expect(index.skills['new-skill'].category).toBe('开发工具');
      expect(index.categories['开发工具']).toContain('new-skill');
      expect(index.stats.totalSkills).toBe(1);
      expect(index.stats.enabledSkills).toBe(1);
    });

    it('should update existing skill in index', () => {
      const index = indexManager.loadIndex();
      const skillMetadata: SkillMetadata = {
        name: 'existing-skill',
        description: 'Original description',
        category: '方法论',
        tags: ['original'],
        path: '/existing',
        metadataPath: '/existing/metadata.json',
        autoGenerated: true,
        customized: false,
        disabled: false
      };

      indexManager.updateSkill(index, skillMetadata);

      const updatedMetadata: SkillMetadata = {
        name: 'existing-skill',
        description: 'Updated description',
        category: '方法论',
        tags: ['updated', 'new-tag'],
        path: '/existing',
        metadataPath: '/existing/metadata.json',
        autoGenerated: false,
        customized: true,
        disabled: false
      };

      indexManager.updateSkill(index, updatedMetadata);

      expect(index.skills['existing-skill'].description).toBe('Updated description');
      expect(index.skills['existing-skill'].tags).toEqual(['updated', 'new-tag']);
      expect(index.skills['existing-skill'].autoGenerated).toBe(false);
      expect(index.skills['existing-skill'].customized).toBe(true);
    });

    it('should move skill between categories', () => {
      const index = indexManager.loadIndex();
      const skillMetadata: SkillMetadata = {
        name: 'moving-skill',
        description: 'Moving skill',
        category: '方法论',
        tags: ['test'],
        path: '/moving',
        metadataPath: '/moving/metadata.json',
        autoGenerated: true,
        customized: false,
        disabled: false
      };

      indexManager.updateSkill(index, skillMetadata);
      expect(index.categories['方法论']).toContain('moving-skill');

      const movedMetadata: SkillMetadata = {
        name: 'moving-skill',
        description: 'Moving skill',
        category: '开发工具',
        tags: ['test'],
        path: '/moving',
        metadataPath: '/moving/metadata.json',
        autoGenerated: true,
        customized: false,
        disabled: false
      };

      indexManager.updateSkill(index, movedMetadata);

      expect(index.categories['方法论']).not.toContain('moving-skill');
      expect(index.categories['开发工具']).toContain('moving-skill');
      expect(index.skills['moving-skill'].category).toBe('开发工具');
    });

    it('should update stats when adding disabled skill', () => {
      const index = indexManager.loadIndex();
      const skillMetadata: SkillMetadata = {
        name: 'disabled-skill',
        description: 'Disabled skill',
        category: '自动化',
        tags: ['auto'],
        path: '/disabled',
        metadataPath: '/disabled/metadata.json',
        autoGenerated: true,
        customized: false,
        disabled: true
      };

      indexManager.updateSkill(index, skillMetadata);

      expect(index.stats.totalSkills).toBe(1);
      expect(index.stats.disabledSkills).toBe(1);
      expect(index.stats.enabledSkills).toBe(0);
    });
  });

  describe('removeSkill', () => {
    it('should remove skill from index', () => {
      const index = indexManager.loadIndex();
      const skillMetadata: SkillMetadata = {
        name: 'removable-skill',
        description: 'Removable skill',
        category: '数据处理',
        tags: ['data'],
        path: '/removable',
        metadataPath: '/removable/metadata.json',
        autoGenerated: true,
        customized: false,
        disabled: false
      };

      indexManager.updateSkill(index, skillMetadata);
      expect(index.skills['removable-skill']).toBeDefined();

      indexManager.removeSkill(index, 'removable-skill');

      expect(index.skills['removable-skill']).toBeUndefined();
      expect(index.categories['数据处理']).not.toContain('removable-skill');
      expect(index.stats.totalSkills).toBe(0);
    });

    it('should handle removing non-existent skill gracefully', () => {
      const index = indexManager.loadIndex();

      expect(() => indexManager.removeSkill(index, 'non-existent-skill')).not.toThrow();
    });

    it('should update category counts and tag counts after removal', () => {
      const index = indexManager.loadIndex();

      const skill1: SkillMetadata = {
        name: 'skill1',
        description: 'Skill 1',
        category: '多媒体',
        tags: ['media', 'video'],
        path: '/skill1',
        metadataPath: '/skill1/metadata.json',
        autoGenerated: true,
        customized: false,
        disabled: false
      };

      const skill2: SkillMetadata = {
        name: 'skill2',
        description: 'Skill 2',
        category: '多媒体',
        tags: ['media', 'audio'],
        path: '/skill2',
        metadataPath: '/skill2/metadata.json',
        autoGenerated: true,
        customized: false,
        disabled: false
      };

      indexManager.updateSkill(index, skill1);
      indexManager.updateSkill(index, skill2);

      expect(index.stats.categoryCounts['多媒体']).toBe(2);
      expect(index.stats.tagCounts['media']).toBe(2);

      indexManager.removeSkill(index, 'skill1');

      expect(index.stats.categoryCounts['多媒体']).toBe(1);
      expect(index.stats.tagCounts['media']).toBe(1);
      expect(index.stats.tagCounts['video']).toBeUndefined();
    });
  });

  describe('category mapping management', () => {
    it('should maintain category-to-skills mapping correctly', () => {
      const index = indexManager.loadIndex();

      const skills: SkillMetadata[] = [
        {
          name: 'skill-a',
          description: 'Skill A',
          category: '方法论',
          tags: ['method'],
          path: '/skill-a',
          metadataPath: '/skill-a/metadata.json',
          autoGenerated: true,
          customized: false,
          disabled: false
        },
        {
          name: 'skill-b',
          description: 'Skill B',
          category: '内容创作',
          tags: ['content'],
          path: '/skill-b',
          metadataPath: '/skill-b/metadata.json',
          autoGenerated: true,
          customized: false,
          disabled: false
        },
        {
          name: 'skill-c',
          description: 'Skill C',
          category: '方法论',
          tags: ['method'],
          path: '/skill-c',
          metadataPath: '/skill-c/metadata.json',
          autoGenerated: true,
          customized: false,
          disabled: false
        }
      ];

      skills.forEach(skill => indexManager.updateSkill(index, skill));

      expect(index.categories['方法论']).toEqual(['skill-a', 'skill-c']);
      expect(index.categories['内容创作']).toEqual(['skill-b']);
      expect(index.categories['开发工具']).toEqual([]);
    });
  });
});