import { SkillRecommender } from '../lib/recommender.js';
import {
  SkillsIndex,
  SkillMetadata,
  Recommendation,
  Category,
} from '../lib/types.js';

describe('SkillRecommender', () => {
  let recommender: SkillRecommender;
  let mockIndex: SkillsIndex;

  beforeEach(() => {
    // Create mock index with sample skills
    mockIndex = {
      version: '1.0.0',
      lastUpdated: new Date().toISOString(),
      categories: {
        方法论: ['swot-analysis', 'pdca-cycle'],
        内容创作: ['article-writer', 'content-optimizer'],
        开发工具: ['code-review', 'api-designer'],
        数据处理: ['data-analyzer', 'data-visualizer'],
        自动化: ['workflow-automation', 'test-automation'],
        多媒体: ['video-generator', 'image-creator'],
        其他: ['helper-tool'],
      },
      skills: {
        'swot-analysis': {
          name: 'swot-analysis',
          description: 'SWOT analysis for strategic planning',
          category: '方法论' as Category,
          tags: ['strategy', 'planning', 'analysis'],
          path: '/skills/swot-analysis',
          metadataPath: '/skills/swot-analysis/metadata.json',
          autoGenerated: true,
          customized: false,
        },
        'pdca-cycle': {
          name: 'pdca-cycle',
          description: 'PDCA cycle for continuous improvement',
          category: '方法论' as Category,
          tags: ['improvement', 'process', 'cycle'],
          path: '/skills/pdca-cycle',
          metadataPath: '/skills/pdca-cycle/metadata.json',
          autoGenerated: true,
          customized: false,
        },
        'article-writer': {
          name: 'article-writer',
          description: 'Write high-quality articles',
          category: '内容创作' as Category,
          tags: ['writing', 'content', 'blog'],
          path: '/skills/article-writer',
          metadataPath: '/skills/article-writer/metadata.json',
          autoGenerated: true,
          customized: false,
        },
        'code-review': {
          name: 'code-review',
          description: 'Review and improve code quality',
          category: '开发工具' as Category,
          tags: ['code', 'review', 'quality'],
          path: '/skills/code-review',
          metadataPath: '/skills/code-review/metadata.json',
          autoGenerated: true,
          customized: false,
        },
        'data-analyzer': {
          name: 'data-analyzer',
          description: 'Analyze data patterns',
          category: '数据处理' as Category,
          tags: ['data', 'analysis', 'statistics'],
          path: '/skills/data-analyzer',
          metadataPath: '/skills/data-analyzer/metadata.json',
          autoGenerated: true,
          customized: false,
        },
      },
      stats: {
        totalSkills: 5,
        enabledSkills: 5,
        disabledSkills: 0,
        categoryCounts: {
          方法论: 2,
          内容创作: 1,
          开发工具: 1,
          数据处理: 1,
          自动化: 0,
          多媒体: 0,
          其他: 0,
        },
        tagCounts: {
          strategy: 1,
          planning: 1,
          analysis: 2,
          improvement: 1,
          process: 1,
          cycle: 1,
          writing: 1,
          content: 1,
          blog: 1,
          code: 1,
          review: 1,
          quality: 1,
          data: 1,
          statistics: 1,
        },
      },
    };

    recommender = new SkillRecommender();
  });

  describe('recommendByQuery', () => {
    it('should recommend skills by name match', () => {
      const results = recommender.recommendByQuery('SWOT', mockIndex, 5);

      expect(results.length).toBeGreaterThan(0);
      const swotResult = results.find((r) => r.skill.name === 'swot-analysis');
      expect(swotResult).toBeDefined();
      expect(swotResult!.matchType).toBe('name');
      expect(swotResult!.score).toBeGreaterThan(0);
    });

    it('should recommend skills by tag match', () => {
      const results = recommender.recommendByQuery('strategy', mockIndex, 5);

      expect(results.length).toBeGreaterThan(0);
      const strategyResult = results.find((r) => r.skill.name === 'swot-analysis');
      expect(strategyResult).toBeDefined();
      expect(strategyResult!.matchType).toBe('tag');
      expect(strategyResult!.score).toBeGreaterThan(0);
    });

    it('should recommend skills by description match', () => {
      const results = recommender.recommendByQuery('strategic', mockIndex, 5);

      expect(results.length).toBeGreaterThan(0);
      const planningResult = results.find(
        (r) => r.skill.name === 'swot-analysis'
      );
      expect(planningResult).toBeDefined();
      expect(planningResult!.matchType).toBe('description');
      expect(planningResult!.score).toBeGreaterThan(0);
    });

    it('should return top N results', () => {
      // Add more skills to mock index
      mockIndex.skills['test-skill-1'] = {
        name: 'test-skill-1',
        description: 'Test skill 1 for testing',
        category: '其他' as Category,
        tags: ['test'],
        path: '/skills/test-skill-1',
        metadataPath: '/skills/test-skill-1/metadata.json',
        autoGenerated: true,
        customized: false,
      };
      mockIndex.skills['test-skill-2'] = {
        name: 'test-skill-2',
        description: 'Test skill 2 for testing',
        category: '其他' as Category,
        tags: ['test'],
        path: '/skills/test-skill-2',
        metadataPath: '/skills/test-skill-2/metadata.json',
        autoGenerated: true,
        customized: false,
      };

      const results = recommender.recommendByQuery('test', mockIndex, 2);

      expect(results.length).toBeLessThanOrEqual(2);
    });

    it('should return empty array for no matches', () => {
      const results = recommender.recommendByQuery('nonexistent', mockIndex, 5);

      expect(results).toEqual([]);
    });

    it('should return empty array for empty query', () => {
      const results = recommender.recommendByQuery('', mockIndex, 5);

      expect(results).toEqual([]);
    });

    it('should exclude disabled skills', () => {
      mockIndex.skills['swot-analysis'].disabled = true;

      const results = recommender.recommendByQuery('SWOT', mockIndex, 5);

      const swotResult = results.find((r) => r.skill.name === 'swot-analysis');
      expect(swotResult).toBeUndefined();
    });

    it('should sort results by score descending', () => {
      const results = recommender.recommendByQuery('analysis', mockIndex, 5);

      for (let i = 1; i < results.length; i++) {
        expect(results[i - 1].score).toBeGreaterThanOrEqual(results[i].score);
      }
    });
  });

  describe('recommendByContext', () => {
    it('should recommend skills based on context keywords', () => {
      const context = {
        userQuery: 'I need to analyze my business strategy',
        conversationHistory: ['We are working on strategic planning'],
      };

      const results = recommender.recommendByContext(context, mockIndex, 5);

      expect(results.length).toBeGreaterThan(0);
      const swotResult = results.find((r) => r.skill.name === 'swot-analysis');
      expect(swotResult).toBeDefined();
    });

    it('should return empty array for empty context', () => {
      const context = {
        userQuery: '',
        conversationHistory: [],
      };

      const results = recommender.recommendByContext(context, mockIndex, 5);

      expect(results).toEqual([]);
    });

    it('should return empty array for null context', () => {
      const results = recommender.recommendByContext(null, mockIndex, 5);

      expect(results).toEqual([]);
    });
  });

  describe('calculateRelevanceScore', () => {
    it('should calculate score based on match type and positions', () => {
      const skill = mockIndex.skills['swot-analysis'];

      // Name match (highest weight)
      const nameScore = recommender['calculateRelevanceScore'](
        skill,
        'SWOT',
        'name'
      );
      expect(nameScore).toBeGreaterThan(0);

      // Tag match
      const tagScore = recommender['calculateRelevanceScore'](
        skill,
        'strategy',
        'tag'
      );
      expect(tagScore).toBeGreaterThan(0);

      // Description match (lowest weight)
      const descScore = recommender['calculateRelevanceScore'](
        skill,
        'planning',
        'description'
      );
      expect(descScore).toBeGreaterThan(0);
    });

    it('should cap score at 100', () => {
      const skill = mockIndex.skills['swot-analysis'];

      // Perfect match should be capped at 100
      const score = recommender['calculateRelevanceScore'](
        skill,
        'swot-analysis',
        'name'
      );

      expect(score).toBeLessThanOrEqual(100);
    });

    it('should return 0 for no match', () => {
      const skill = mockIndex.skills['swot-analysis'];

      const score = recommender['calculateRelevanceScore'](
        skill,
        'nonexistent',
        'description'
      );

      expect(score).toBe(0);
    });

    it('should give higher score for exact match than partial match', () => {
      const skill = mockIndex.skills['swot-analysis'];

      const exactScore = recommender['calculateRelevanceScore'](
        skill,
        'swot-analysis',
        'name'
      );

      const partialScore = recommender['calculateRelevanceScore'](
        skill,
        'swot',
        'name'
      );

      expect(exactScore).toBeGreaterThan(partialScore);
    });
  });

  describe('accumulateScore', () => {
    it('should accumulate scores from multiple matches', () => {
      const skill = mockIndex.skills['swot-analysis'];

      // Simulate multiple matches
      const nameScore = recommender['calculateRelevanceScore'](
        skill,
        'swot',
        'name'
      );
      const tagScore = recommender['calculateRelevanceScore'](
        skill,
        'analysis',
        'tag'
      );

      const accumulatedScore = recommender['accumulateScore'](
        nameScore,
        tagScore
      );

      expect(accumulatedScore).toBeGreaterThan(nameScore);
      expect(accumulatedScore).toBeGreaterThan(tagScore);
    });

    it('should cap accumulated score at 100', () => {
      // Add two high scores that would exceed 100
      const score1 = 80;
      const score2 = 80;

      const accumulatedScore = recommender['accumulateScore'](score1, score2);

      expect(accumulatedScore).toBeLessThanOrEqual(100);
    });

    it('should handle zero scores', () => {
      const score1 = 0;
      const score2 = 50;

      const accumulatedScore = recommender['accumulateScore'](score1, score2);

      expect(accumulatedScore).toBe(50);
    });
  });

  describe('generateReason', () => {
    it('should generate reason for name match', () => {
      const reason = recommender['generateReason'](
        'swot-analysis',
        'SWOT',
        'name'
      );

      expect(reason).toContain('name');
      expect(reason).toContain('SWOT');
    });

    it('should generate reason for tag match', () => {
      const reason = recommender['generateReason'](
        'swot-analysis',
        'strategy',
        'tag'
      );

      expect(reason).toContain('tag');
      expect(reason).toContain('strategy');
    });

    it('should generate reason for description match', () => {
      const reason = recommender['generateReason'](
        'swot-analysis',
        'planning',
        'description'
      );

      expect(reason).toContain('description');
      expect(reason).toContain('planning');
    });
  });

  describe('determineMatchType', () => {
    it('should identify name match', () => {
      const skill = mockIndex.skills['swot-analysis'];

      const matchType = recommender['determineMatchType'](skill, 'SWOT');

      expect(matchType).toBe('name');
    });

    it('should identify tag match', () => {
      const skill = mockIndex.skills['swot-analysis'];

      const matchType = recommender['determineMatchType'](skill, 'strategy');

      expect(matchType).toBe('tag');
    });

    it('should identify description match', () => {
      const skill = mockIndex.skills['swot-analysis'];

      const matchType = recommender['determineMatchType'](
        skill,
        'strategic'
      );

      expect(matchType).toBe('description');
    });

    it('should return null for no match', () => {
      const skill = mockIndex.skills['swot-analysis'];

      const matchType = recommender['determineMatchType'](skill, 'nonexistent');

      expect(matchType).toBeNull();
    });
  });

  describe('extractKeywords', () => {
    it('should extract keywords from query', () => {
      const keywords = recommender['extractKeywords'](
        'I need to analyze my business strategy'
      );

      expect(keywords).toContain('analyze');
      expect(keywords).toContain('business');
      expect(keywords).toContain('strategy');
    });

    it('should handle empty string', () => {
      const keywords = recommender['extractKeywords']('');

      expect(keywords).toEqual([]);
    });

    it('should filter common words', () => {
      const keywords = recommender['extractKeywords'](
        'the and a to for with I need'
      );

      expect(keywords).not.toContain('the');
      expect(keywords).not.toContain('and');
      expect(keywords).not.toContain('a');
      expect(keywords).not.toContain('to');
    });

    it('should handle single word', () => {
      const keywords = recommender['extractKeywords']('analysis');

      expect(keywords).toContain('analysis');
    });
  });
});