// 预定义分类类型
export type Category =
  | '方法论'
  | '内容创作'
  | '开发工具'
  | '数据处理'
  | '自动化'
  | '多媒体'
  | '其他';

// Skill 基础信息
export interface SkillBasicInfo {
  name: string;
  description: string;
  path: string;
  disabled: boolean;
}

// Skill 完整元数据
export interface SkillMetadata {
  name: string;
  description: string;
  category: Category;
  tags: string[];
  path: string;
  metadataPath: string;
  autoGenerated: boolean;
  generatedAt?: string;
  customized: boolean;
  disabled?: boolean;
}

// 预定义规则
export interface PredefinedRule {
  keywords: string[];
  category: Category;
  tags: string[];
}

// 全局索引
export interface SkillsIndex {
  version: string;
  lastUpdated: string;
  categories: Record<Category, string[]>;
  skills: Record<string, SkillMetadata>;
  stats: IndexStats;
}

// 索引统计信息
export interface IndexStats {
  totalSkills: number;
  enabledSkills: number;
  disabledSkills: number;
  categoryCounts: Record<Category, number>;
  tagCounts: Record<string, number>;
}

// 分类结果
export interface ClassificationResult {
  category: Category;
  tags: string[];
  method: 'rule-based' | 'llm-based';
  confidence: number;
}

// 推荐结果
export interface Recommendation {
  skill: SkillMetadata;
  score: number;
  reason: string;
  matchType: 'name' | 'description' | 'tag' | 'category';
}

// 同步结果
export interface SyncResult {
  added: number;
  removed: number;
  updated: number;
}

// 预定义配置
export interface MetadataConfig {
  categories: Category[];
  rules: PredefinedRule[];
}

// 规则匹配结果
export interface RuleMatch {
  category: Category;
  tags: string[];
}