#!/usr/bin/env node
/**
 * Recommend Command - Recommend skills based on query with detailed scoring
 *
 * Usage:
 *   node scripts/recommend.js <query> [--limit <n>] [--detailed]
 *
 * Options:
 *   --limit: Maximum number of results (default: 5)
 *   --detailed: Show detailed scoring breakdown
 */

import * as path from 'path';
import { fileURLToPath } from 'url';
import { IndexManager } from '../lib/indexer.js';
import { SkillRecommender } from '../lib/recommender.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Default paths
const DEFAULT_INDEX_PATH = path.join(__dirname, '..', 'index.json');

/**
 * Parse command line arguments
 */
function parseArgs(args: string[]) {
  const options: {
    query?: string;
    limit: number;
    detailed: boolean;
    indexPath?: string;
  } = {
    limit: 5,
    detailed: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    switch (arg) {
      case '--limit':
        if (args[i + 1]) {
          options.limit = parseInt(args[++i], 10);
        }
        break;
      case '--detailed':
        options.detailed = true;
        break;
      case '--index-path':
        if (args[i + 1]) {
          options.indexPath = args[++i];
        }
        break;
      default:
        if (!options.query && !arg.startsWith('--')) {
          options.query = arg;
        }
    }
  }

  return options;
}

/**
 * Display recommendation with detailed scoring
 */
function displayRecommendation(result: any, rank: number, detailed: boolean): void {
  const skill = result.skill;
  const status = skill.disabled ? '❌' : '✓';

  console.log(`\n${rank}. ${status} ${skill.name}`);
  console.log(`   Category: ${skill.category}`);
  console.log(`   Score: ${result.score.toFixed(1)}/100`);
  console.log(`   Match Type: ${result.matchType}`);
  console.log(`   Reason: ${result.reason}`);

  if (detailed) {
    console.log(`\n   📋 Details:`);
    console.log(`   Description: ${skill.description}`);
    console.log(`   Tags: ${skill.tags.join(', ') || 'none'}`);
    console.log(`   Path: ${skill.path}`);
    console.log(`   Disabled: ${skill.disabled ? 'yes' : 'no'}`);

    if (skill.autoGenerated) {
      console.log(`   Auto-generated: yes (${skill.generatedAt})`);
    } else {
      console.log(`   Auto-generated: no (customized)`);
    }
  }
}

/**
 * Display recommendations
 */
function displayRecommendations(results: any[], query: string, detailed: boolean): void {
  if (results.length === 0) {
    console.log(`\n❌ No recommendations for "${query}"`);
    console.log('Try a different query or run init to update the index.');
    return;
  }

  console.log(`\n💡 Top ${results.length} recommendations for "${query}":`);

  results.forEach((result, index) => {
    displayRecommendation(result, index + 1, detailed);
  });

  console.log(`\n💡 Tips:`);
  console.log('  - Use "node scripts/search.js <query>" for more search options');
  console.log('  - Use "node scripts/list.js --category <category>" to browse by category');
  console.log('  - Use "node scripts/stats.js" for detailed statistics');
}

/**
 * Main recommend function
 */
async function recommend() {
  const args = process.argv.slice(2);
  const options = parseArgs(args);

  if (!options.query) {
    console.error('Error: Query is required');
    console.error('Usage: node scripts/recommend.js <query> [options]');
    console.error('Options:');
    console.error('  --limit <n>     Maximum number of results (default: 5)');
    console.error('  --detailed      Show detailed scoring breakdown');
    console.error('  --index-path    Custom index path');
    process.exit(1);
  }

  const indexPath = options.indexPath || DEFAULT_INDEX_PATH;

  // Load index
  const indexManager = new IndexManager(indexPath);
  const index = indexManager.loadIndex();

  if (index.stats.totalSkills === 0) {
    console.error('Error: No skills in index. Run init command first.');
    process.exit(1);
  }

  // Recommend
  const recommender = new SkillRecommender();
  const results = recommender.recommendByQuery(options.query, index, options.limit);

  // Display recommendations
  displayRecommendations(results, options.query, options.detailed);
}

// Run recommend
recommend().catch((error) => {
  console.error('Error during recommendation:', error);
  process.exit(1);
});